[build]
  command = "npm run build"
  publish = "dist/client"

[build.environment]
  NODE_VERSION = "22"
  NITRO_PRESET = "netlify"
  VITE_API_URL = "https://fahad-weaving-backend-lake.vercel.app/api/v1"
