// Constants, initial data, and schema for User Management module

export const COMPANIES = [
  { id: "comp_1", name: "ABC Weaving Mills Ltd", code: "ABCW", type: "Main Company (Headquarters)" },
  { id: "comp_2", name: "ABC Textiles Ltd", code: "ABCT", type: "Spinning & Weaving Division" },
  { id: "comp_3", name: "ABC Logistics & Garments", code: "ABCL", type: "Apparel & Exports Division" },
];

export const BRANCHES = [
  { id: "br_1", companyId: "comp_1", companyName: "ABC Weaving Mills Ltd", name: "Head Office - Karachi", city: "Karachi", code: "HO-KHI" },
  { id: "br_2", companyId: "comp_1", companyName: "ABC Weaving Mills Ltd", name: "Factory 01 - SITE Industrial Area", city: "Karachi", code: "FAC-01" },
  { id: "br_3", companyId: "comp_2", companyName: "ABC Textiles Ltd", name: "Factory 02 - Faisalabad Industrial Estate", city: "Faisalabad", code: "FAC-02" },
  { id: "br_4", companyId: "comp_3", companyName: "ABC Logistics & Garments", name: "Warehouse 03 - Lahore Hub", city: "Lahore", code: "WH-LHR" },
];

export const DEPARTMENTS = [
  "Administration",
  "Accounts",
  "HR",
  "Production",
  "Sizing",
  "Loom",
  "Warehouse",
  "Purchase",
  "Sales",
  "Maintenance",
  "IT",
];

export const DESIGNATIONS = [
  "System Administrator",
  "IT Support Specialist",
  "Senior Accountant",
  "Accounts Officer",
  "Accounts Trainee",
  "HR Manager",
  "HR Executive",
  "Production Manager",
  "Floor Supervisor",
  "Sizing Master",
  "Loom Master",
  "Machine Operator",
  "Quality Inspector",
  "Warehouse Manager",
  "Store Keeper",
  "Purchase Manager",
  "Purchase Officer",
  "Senior Sales Executive",
  "Sales Officer",
  "Electrical Engineer",
  "Mechanical Technician",
  "Shift Incharge",
  "Internal Auditor",
];

export const USER_STATUSES = ["Active", "Inactive", "Suspended", "Pending"];

export const ROLES_LIST = [
  "Super Admin",
  "Admin",
  "Production Manager",
  "Manager",
  "Accountant",
  "HR",
  "Supervisor",
  "Operator",
  "Employee",
  "Viewer",
];

export const SHIFTS = [
  "Morning (08:00 - 17:00)",
  "Evening (14:00 - 23:00)",
  "Night (22:00 - 07:00)",
  "General (09:00 - 18:00)",
];

export const GENDERS = ["Male", "Female", "Other", "Prefer not to say"];

// Module Permissions Schema
export const PERMISSION_MODULES = [
  {
    id: "dashboard",
    name: "Dashboard",
    description: "Executive dashboards, KPI widgets, and system overview",
    permissions: [
      { id: "dashboard.view", name: "View Dashboard", description: "Access overview metrics and charts" },
      { id: "dashboard.export", name: "Export Analytics", description: "Download dashboard summary reports" },
    ],
  },
  {
    id: "user_management",
    name: "User Management",
    description: "User accounts, roles, access permissions, and audit logs",
    permissions: [
      { id: "users.view", name: "View Users", description: "Browse user list and user profile details" },
      { id: "users.add", name: "Add User", description: "Create new user accounts" },
      { id: "users.edit", name: "Edit User", description: "Modify user profile and work data" },
      { id: "users.delete", name: "Delete User", description: "Remove user accounts from the system" },
      { id: "users.status", name: "Change Status", description: "Activate, deactivate, or suspend users" },
      { id: "users.reset_pwd", name: "Reset Password", description: "Initiate password reset for users" },
      { id: "roles.manage", name: "Manage Roles & Permissions", description: "Configure system roles and permission sets" },
      { id: "activity.view", name: "View Audit Activity", description: "Inspect system security and login logs" },
    ],
  },
  {
    id: "raw_manufacturing",
    name: "Raw Manufacturing",
    description: "Complete textile production cycle from yarn to grey cloth",
    permissions: [
      { id: "mfg.view", name: "View Manufacturing Flow", description: "View manufacturing stats and tracking" },
      { id: "mfg.add", name: "Add Manufacturing Entry", description: "Create intake and sizing batches" },
      { id: "mfg.edit", name: "Edit Records", description: "Modify ongoing batch details" },
      { id: "mfg.delete", name: "Delete Records", description: "Delete manufacturing entries" },
      { id: "mfg.assign", name: "Assign Beams & Looms", description: "Allocate beams and start loom production" },
      { id: "mfg.status", name: "Update Production Status", description: "Change status from Running to Maintenance/Stopped" },
    ],
  },
  {
    id: "raw_material",
    name: "Raw Material (Yarn Intake)",
    description: "Yarn receiving, lot tracking, bag & cone calculations",
    permissions: [
      { id: "yarn.view", name: "View Raw Materials", description: "Browse yarn stock and lot numbers" },
      { id: "yarn.add", name: "Intake Yarn", description: "Record new yarn arrivals and vendor lots" },
      { id: "yarn.edit", name: "Edit Yarn Details", description: "Update weight, rate, and counts" },
      { id: "yarn.delete", name: "Delete Yarn Record", description: "Remove mistaken yarn entries" },
    ],
  },
  {
    id: "sizing",
    name: "Sizing Operations",
    description: "Yarn sizing, beam winding, chemical sizing recipe logs",
    permissions: [
      { id: "sizing.view", name: "View Sizing Orders", description: "Track sized beams and yardage" },
      { id: "sizing.add", name: "Create Sizing Batch", description: "Issue yarn to sizing machines" },
      { id: "sizing.edit", name: "Edit Sizing Entry", description: "Modify sizing formula and yardage" },
      { id: "sizing.delete", name: "Delete Sizing Entry", description: "Delete sizing records" },
    ],
  },
  {
    id: "beams",
    name: "Warp Beams",
    description: "Beam inventory, cuts, ends, length, and loom allocation",
    permissions: [
      { id: "beams.view", name: "View Beams", description: "Inspect available and assigned beams" },
      { id: "beams.add", name: "Add Beam Record", description: "Create warp beam entry" },
      { id: "beams.edit", name: "Edit Beam Details", description: "Update beam parameters and length" },
      { id: "beams.delete", name: "Delete Beam", description: "Delete beam record" },
      { id: "beams.assign", name: "Assign to Loom", description: "Mount beam on active loom" },
    ],
  },
  {
    id: "looms",
    name: "Looms & Weaving Shed",
    description: "Power & airjet looms, RPM, efficiency, daily meterage logs",
    permissions: [
      { id: "looms.view", name: "View Looms", description: "Monitor loom status and fabric output" },
      { id: "looms.add", name: "Add Loom", description: "Register new loom machine in system" },
      { id: "looms.edit", name: "Edit Loom Config", description: "Modify loom type, RPM, and width" },
      { id: "looms.delete", name: "Delete Loom", description: "Decommission or delete loom" },
      { id: "looms.assign_beam", name: "Mount / Dismount Beam", description: "Change active beam on loom" },
      { id: "looms.production", name: "Record Daily Meters", description: "Log daily fabric production count" },
    ],
  },
  {
    id: "purchases",
    name: "Purchasing & Vendors",
    description: "Purchase orders, raw material vendors, payment tracking",
    permissions: [
      { id: "po.view", name: "View Purchases", description: "Browse purchase orders and vendor ledgers" },
      { id: "po.add", name: "Create Purchase Order", description: "Issue new purchase orders" },
      { id: "po.edit", name: "Edit Purchase Order", description: "Modify PO quantities and rates" },
      { id: "po.delete", name: "Delete PO", description: "Cancel or remove purchase order" },
      { id: "po.approve", name: "Approve PO", description: "Authorize purchase payment and intake" },
    ],
  },
  {
    id: "sales",
    name: "Sales & Invoicing",
    description: "Customer sales orders, fabric delivery, receivables",
    permissions: [
      { id: "sale.view", name: "View Sales", description: "Browse invoices and customer orders" },
      { id: "sale.add", name: "Create Sales Invoice", description: "Bill customers for grey fabric rolls" },
      { id: "sale.edit", name: "Edit Invoice", description: "Modify price, meters, or terms" },
      { id: "sale.delete", name: "Delete Invoice", description: "Void sales transaction" },
      { id: "sale.dispatch", name: "Mark Dispatched", description: "Record gate pass and dispatch" },
    ],
  },
  {
    id: "inventory",
    name: "Inventory & Stores",
    description: "Warehouse stock balances, minimum thresholds, stock adjustments",
    permissions: [
      { id: "inv.view", name: "View Inventory", description: "Inspect items, spares, and yarn stock" },
      { id: "inv.add", name: "Add Item", description: "Create new inventory item SKU" },
      { id: "inv.edit", name: "Edit Item", description: "Update minimum stock and prices" },
      { id: "inv.delete", name: "Delete Item", description: "Remove inventory item" },
      { id: "inv.adjust", name: "Adjust Stock", description: "Perform manual stock audit adjustment" },
    ],
  },
  {
    id: "workforce",
    name: "Employees & Payroll",
    description: "Workforce directory, wage calculation, salary slips",
    permissions: [
      { id: "emp.view", name: "View Employees", description: "Browse worker records and salaries" },
      { id: "emp.add", name: "Add Employee", description: "Onboard new factory staff" },
      { id: "emp.edit", name: "Edit Employee", description: "Update wages, designation, and CNIC" },
      { id: "emp.delete", name: "Delete Employee", description: "Offboard employee from records" },
      { id: "payroll.process", name: "Process Payroll", description: "Generate monthly payroll & pay slips" },
    ],
  },
  {
    id: "attendance",
    name: "Attendance & Shifts",
    description: "Daily biometric check-in/out, shift roster, overtime",
    permissions: [
      { id: "att.view", name: "View Attendance Log", description: "Inspect daily workforce clock-in" },
      { id: "att.mark", name: "Mark Attendance", description: "Record manual check-in or late entry" },
      { id: "att.edit", name: "Edit Attendance", description: "Correct check-in/out time stamps" },
      { id: "att.export", name: "Export Attendance", description: "Download monthly attendance sheet" },
    ],
  },
  {
    id: "reports",
    name: "Reports & Financials",
    description: "Production output, yarn consumption, P&L, balance sheets",
    permissions: [
      { id: "rep.view", name: "View Reports", description: "Access reporting analytics" },
      { id: "rep.generate", name: "Generate Reports", description: "Run custom date-range queries" },
      { id: "rep.export", name: "Export PDF/Excel", description: "Download formal PDF balance statements" },
    ],
  },
  {
    id: "settings",
    name: "System Settings",
    description: "Company registration, security policies, backup configurations",
    permissions: [
      { id: "settings.view", name: "View Settings", description: "Inspect system setup" },
      { id: "settings.company", name: "Edit Company Profile", description: "Update business registration & address" },
      { id: "settings.security", name: "Security Policies", description: "Manage 2FA, session timeouts, and IP rules" },
    ],
  },
];

// Flat list of all permission IDs
export const ALL_PERMISSION_IDS = PERMISSION_MODULES.flatMap((m) => m.permissions.map((p) => p.id));

// Role definitions
export const INITIAL_ROLES = [
  {
    id: "role_super_admin",
    name: "Super Admin",
    description: "Unrestricted system access with authority to modify core ERP configurations and grant permissions.",
    userCount: 2,
    permissions: [...ALL_PERMISSION_IDS],
    status: "Active",
    isSystem: true,
    color: "primary",
  },
  {
    id: "role_admin",
    name: "Admin",
    description: "Administrative access across operations, employees, reports, inventory, and user accounts.",
    userCount: 3,
    permissions: ALL_PERMISSION_IDS.filter((p) => !p.startsWith("settings.security")),
    status: "Active",
    isSystem: true,
    color: "info",
  },
  {
    id: "role_prod_mgr",
    name: "Production Manager",
    description: "Comprehensive control over raw manufacturing, yarn inventory, sizing batches, beams, and loom machines.",
    userCount: 4,
    permissions: [
      "dashboard.view", "dashboard.export",
      "mfg.view", "mfg.add", "mfg.edit", "mfg.assign", "mfg.status",
      "yarn.view", "yarn.add", "yarn.edit",
      "sizing.view", "sizing.add", "sizing.edit",
      "beams.view", "beams.add", "beams.edit", "beams.assign",
      "looms.view", "looms.add", "looms.edit", "looms.assign_beam", "looms.production",
      "inv.view", "inv.add", "inv.edit", "inv.adjust",
      "att.view", "att.mark",
      "rep.view", "rep.generate", "rep.export"
    ],
    status: "Active",
    isSystem: false,
    color: "success",
  },
  {
    id: "role_manager",
    name: "Manager",
    description: "Operations supervisor with approval capabilities across sales, purchases, and factory floor logs.",
    userCount: 5,
    permissions: [
      "dashboard.view", "dashboard.export",
      "mfg.view", "mfg.assign", "mfg.status",
      "yarn.view", "sizing.view", "beams.view", "looms.view", "looms.production",
      "po.view", "po.approve",
      "sale.view", "sale.dispatch",
      "inv.view", "inv.adjust",
      "emp.view", "att.view", "att.mark",
      "rep.view", "rep.generate"
    ],
    status: "Active",
    isSystem: false,
    color: "purple",
  },
  {
    id: "role_accountant",
    name: "Accountant",
    description: "Financial ledger management, purchasing approvals, billing, sales invoices, and payroll computation.",
    userCount: 4,
    permissions: [
      "dashboard.view", "dashboard.export",
      "po.view", "po.add", "po.edit", "po.approve",
      "sale.view", "sale.add", "sale.edit",
      "inv.view",
      "emp.view", "payroll.process",
      "rep.view", "rep.generate", "rep.export"
    ],
    status: "Active",
    isSystem: false,
    color: "warning",
  },
  {
    id: "role_hr",
    name: "HR",
    description: "Human resource management, employee onboarding, attendance tracking, and shift roster management.",
    userCount: 2,
    permissions: [
      "dashboard.view",
      "users.view", "users.add", "users.edit", "users.status", "users.reset_pwd",
      "emp.view", "emp.add", "emp.edit", "payroll.process",
      "att.view", "att.mark", "att.edit", "att.export",
      "rep.view"
    ],
    status: "Active",
    isSystem: false,
    color: "rose",
  },
  {
    id: "role_supervisor",
    name: "Supervisor",
    description: "On-floor supervision for loom sheds and sizing departments; marks daily attendance and machine meters.",
    userCount: 6,
    permissions: [
      "dashboard.view",
      "mfg.view", "mfg.status",
      "yarn.view", "sizing.view", "sizing.add",
      "beams.view", "beams.assign",
      "looms.view", "looms.assign_beam", "looms.production",
      "att.view", "att.mark"
    ],
    status: "Active",
    isSystem: false,
    color: "emerald",
  },
  {
    id: "role_operator",
    name: "Operator",
    description: "Loom and machine operator access to log meters and inspect job assignments.",
    userCount: 14,
    permissions: [
      "dashboard.view",
      "looms.view", "looms.production",
      "att.view"
    ],
    status: "Active",
    isSystem: false,
    color: "cyan",
  },
  {
    id: "role_employee",
    name: "Employee",
    description: "Self-service portal to check attendance records, leave history, and monthly pay slips.",
    userCount: 88,
    permissions: [
      "dashboard.view",
      "att.view"
    ],
    status: "Active",
    isSystem: false,
    color: "muted",
  },
  {
    id: "role_viewer",
    name: "Viewer",
    description: "Read-only access to factory dashboards, reports, and production statistics for external auditors.",
    userCount: 4,
    permissions: [
      "dashboard.view",
      "mfg.view", "yarn.view", "sizing.view", "beams.view", "looms.view",
      "po.view", "sale.view", "inv.view", "emp.view", "att.view", "rep.view"
    ],
    status: "Active",
    isSystem: false,
    color: "slate",
  },
];

// Initial Realistic Users Data
export const INITIAL_USERS = [
  {
    id: "USR-001",
    username: "admin",
    fullName: "Muhammad Ahmed",
    firstName: "Muhammad",
    lastName: "Ahmed",
    email: "admin@fahadweaving.com",
    phone: "+92 300 8492011",
    altPhone: "+92 42 35918800",
    dob: "1988-04-14",
    gender: "Male",
    role: "Super Admin",
    department: "Administration",
    designation: "System Administrator",
    employeeId: "EMP-001",
    company: "ABC Weaving Mills Ltd",
    branch: "Head Office - Karachi",
    status: "Active",
    joiningDate: "2019-01-15",
    manager: "Board of Directors",
    shift: "General (09:00 - 18:00)",
    address: "Suite 402, Al-Hafeez Heights, Gulberg III",
    city: "Lahore",
    state: "Punjab",
    country: "Pakistan",
    postalCode: "54000",
    notes: "Primary ERP administrator with superuser authorization across all factory branches.",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2030-12-31",
    lastLogin: "2026-09-28 10:42 AM",
    createdDate: "2019-01-15",
    twoFactorEnabled: true,
  },
  {
    id: "USR-002",
    username: "production.manager",
    fullName: "Ali Raza",
    firstName: "Ali",
    lastName: "Raza",
    email: "production@fahadweaving.com",
    phone: "+92 321 9988771",
    altPhone: "+92 300 4433221",
    dob: "1985-08-22",
    gender: "Male",
    role: "Production Manager",
    department: "Production",
    designation: "Production Manager",
    employeeId: "EMP-025",
    company: "ABC Weaving Mills Ltd",
    branch: "Factory 01 - SITE Industrial Area",
    status: "Active",
    joiningDate: "2020-03-01",
    manager: "Muhammad Ahmed",
    shift: "Morning (08:00 - 17:00)",
    address: "Plot 18, Block B, North Nazimabad",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "74600",
    notes: "Supervises 48 Tsudakoma looms, sizing recipes, and raw yarn quality inspections.",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2028-12-31",
    lastLogin: "2026-09-28 08:15 AM",
    createdDate: "2020-03-01",
    twoFactorEnabled: true,
  },
  {
    id: "USR-003",
    username: "accountant",
    fullName: "Hassan Khan",
    firstName: "Hassan",
    lastName: "Khan",
    email: "accounts@fahadweaving.com",
    phone: "+92 333 1245780",
    altPhone: "+92 21 32556677",
    dob: "1991-11-05",
    gender: "Male",
    role: "Accountant",
    department: "Accounts",
    designation: "Senior Accountant",
    employeeId: "EMP-031",
    company: "ABC Weaving Mills Ltd",
    branch: "Head Office - Karachi",
    status: "Active",
    joiningDate: "2021-06-10",
    manager: "Muhammad Ahmed",
    shift: "General (09:00 - 18:00)",
    address: "House 114, Street 7, DHA Phase 5",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "75500",
    notes: "Handles yarn supplier invoicing, cloth buyer payment receipts, and monthly payroll.",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2028-06-30",
    lastLogin: "2026-09-28 09:30 AM",
    createdDate: "2021-06-10",
    twoFactorEnabled: true,
  },
  {
    id: "USR-004",
    username: "hr.fatima",
    fullName: "Fatima Noor",
    firstName: "Fatima",
    lastName: "Noor",
    email: "hr@fahadweaving.com",
    phone: "+92 301 9876543",
    altPhone: "+92 42 35789012",
    dob: "1993-02-18",
    gender: "Female",
    role: "HR",
    department: "HR",
    designation: "HR Manager",
    employeeId: "EMP-002",
    company: "ABC Weaving Mills Ltd",
    branch: "Head Office - Karachi",
    status: "Active",
    joiningDate: "2021-07-04",
    manager: "Muhammad Ahmed",
    shift: "General (09:00 - 18:00)",
    address: "Bungalow 45-C, Model Town",
    city: "Lahore",
    state: "Punjab",
    country: "Pakistan",
    postalCode: "54700",
    notes: "Oversees workforce recruitment, shift assignments, biometric sync, and performance appraisals.",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2029-07-01",
    lastLogin: "2026-09-28 09:02 AM",
    createdDate: "2021-07-04",
    twoFactorEnabled: false,
  },
  {
    id: "USR-005",
    username: "bilal.loom",
    fullName: "Bilal Ahmed",
    firstName: "Bilal",
    lastName: "Ahmed",
    email: "bilal.loom@fahadweaving.com",
    phone: "+92 333 5551122",
    altPhone: "",
    dob: "1989-09-12",
    gender: "Male",
    role: "Supervisor",
    department: "Loom",
    designation: "Floor Supervisor",
    employeeId: "EMP-003",
    company: "ABC Weaving Mills Ltd",
    branch: "Factory 01 - SITE Industrial Area",
    status: "Active",
    joiningDate: "2022-01-20",
    manager: "Ali Raza",
    shift: "Morning (08:00 - 17:00)",
    address: "Quarter 12, Mill Colony, SITE Area",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "75700",
    notes: "Lead supervisor for Shed A airjet looms. Expert in beam changeovers and knotting.",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2027-12-31",
    lastLogin: "2026-09-28 07:50 AM",
    createdDate: "2022-01-20",
    twoFactorEnabled: false,
  },
  {
    id: "USR-006",
    username: "usman.store",
    fullName: "Usman Tariq",
    firstName: "Usman",
    lastName: "Tariq",
    email: "usman.store@fahadweaving.com",
    phone: "+92 345 7788990",
    altPhone: "",
    dob: "1990-12-30",
    gender: "Male",
    role: "Manager",
    department: "Warehouse",
    designation: "Warehouse Manager",
    employeeId: "EMP-005",
    company: "ABC Logistics & Garments",
    branch: "Warehouse 03 - Lahore Hub",
    status: "Active",
    joiningDate: "2022-08-30",
    manager: "Ali Raza",
    shift: "Morning (08:00 - 17:00)",
    address: "House 28, St 4, Multan Road",
    city: "Lahore",
    state: "Punjab",
    country: "Pakistan",
    postalCode: "54000",
    notes: "Manages central yarn warehouse and finished grey cloth storage before client dispatch.",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2027-08-31",
    lastLogin: "2026-09-27 04:30 PM",
    createdDate: "2022-08-30",
    twoFactorEnabled: false,
  },
  {
    id: "USR-007",
    username: "sana.sales",
    fullName: "Sana Iqbal",
    firstName: "Sana",
    lastName: "Iqbal",
    email: "sana.sales@fahadweaving.com",
    phone: "+92 311 6655443",
    altPhone: "",
    dob: "1994-05-16",
    gender: "Female",
    role: "Employee",
    department: "Sales",
    designation: "Senior Sales Executive",
    employeeId: "EMP-006",
    company: "ABC Weaving Mills Ltd",
    branch: "Head Office - Karachi",
    status: "Inactive",
    joiningDate: "2023-06-10",
    manager: "Muhammad Ahmed",
    shift: "General (09:00 - 18:00)",
    address: "Apartment 5B, Clifton Block 2",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "75600",
    notes: "Currently on maternity leave. Account temporarily set to inactive.",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2027-06-10",
    lastLogin: "2026-08-15 02:10 PM",
    createdDate: "2023-06-10",
    twoFactorEnabled: false,
  },
  {
    id: "USR-008",
    username: "hamza.qc",
    fullName: "Hamza Raza",
    firstName: "Hamza",
    lastName: "Raza",
    email: "hamza.qc@fahadweaving.com",
    phone: "+92 302 1010202",
    altPhone: "",
    dob: "1992-07-09",
    gender: "Male",
    role: "Supervisor",
    department: "Production",
    designation: "Quality Inspector",
    employeeId: "EMP-007",
    company: "ABC Weaving Mills Ltd",
    branch: "Factory 01 - SITE Industrial Area",
    status: "Active",
    joiningDate: "2021-02-18",
    manager: "Ali Raza",
    shift: "Night (22:00 - 07:00)",
    address: "Block 14, Gulshan-e-Iqbal",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "75300",
    notes: "Conducts yarn CSP testing, sizing pickup validation, and 4-point fabric inspection.",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2028-02-28",
    lastLogin: "2026-09-28 06:10 AM",
    createdDate: "2021-02-18",
    twoFactorEnabled: false,
  },
  {
    id: "USR-009",
    username: "mariam.purchase",
    fullName: "Mariam Sheikh",
    firstName: "Mariam",
    lastName: "Sheikh",
    email: "mariam.purchase@fahadweaving.com",
    phone: "+92 308 7172829",
    altPhone: "",
    dob: "1995-03-27",
    gender: "Female",
    role: "Accountant",
    department: "Purchase",
    designation: "Purchase Officer",
    employeeId: "EMP-014",
    company: "ABC Textiles Ltd",
    branch: "Factory 02 - Faisalabad Industrial Estate",
    status: "Active",
    joiningDate: "2022-12-01",
    manager: "Hassan Khan",
    shift: "General (09:00 - 18:00)",
    address: "Street 9, Madina Town",
    city: "Faisalabad",
    state: "Punjab",
    country: "Pakistan",
    postalCode: "38000",
    notes: "Maintains vendor quotes for 30s/40s cotton cones, sizing chemicals, and machine spares.",
    avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2027-12-01",
    lastLogin: "2026-09-28 11:15 AM",
    createdDate: "2022-12-01",
    twoFactorEnabled: false,
  },
  {
    id: "USR-010",
    username: "tariq.sizing",
    fullName: "Tariq Mehmood",
    firstName: "Tariq",
    lastName: "Mehmood",
    email: "tariq.sizing@fahadweaving.com",
    phone: "+92 300 6677881",
    altPhone: "",
    dob: "1982-10-10",
    gender: "Male",
    role: "Supervisor",
    department: "Sizing",
    designation: "Sizing Master",
    employeeId: "EMP-019",
    company: "ABC Weaving Mills Ltd",
    branch: "Factory 01 - SITE Industrial Area",
    status: "Active",
    joiningDate: "2019-11-15",
    manager: "Ali Raza",
    shift: "Morning (08:00 - 17:00)",
    address: "Plot 33, Sector 5G, New Karachi",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "75850",
    notes: "Master technician for Benninger sizing range with 20+ years of textile experience.",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2029-11-15",
    lastLogin: "2026-09-28 07:30 AM",
    createdDate: "2019-11-15",
    twoFactorEnabled: false,
  },
  {
    id: "USR-011",
    username: "zainab.it",
    fullName: "Zainab Bibi",
    firstName: "Zainab",
    lastName: "Bibi",
    email: "zainab.it@fahadweaving.com",
    phone: "+92 334 9911223",
    altPhone: "",
    dob: "1996-09-14",
    gender: "Female",
    role: "Admin",
    department: "IT",
    designation: "IT Support Specialist",
    employeeId: "EMP-008",
    company: "ABC Weaving Mills Ltd",
    branch: "Head Office - Karachi",
    status: "Active",
    joiningDate: "2023-02-01",
    manager: "Muhammad Ahmed",
    shift: "General (09:00 - 18:00)",
    address: "Block 7, Gulshan-e-Iqbal",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "75300",
    notes: "Maintains network firewalls, ERP database backups, and biometric attendance devices.",
    avatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2028-02-01",
    lastLogin: "2026-09-28 10:12 AM",
    createdDate: "2023-02-01",
    twoFactorEnabled: true,
  },
  {
    id: "USR-012",
    username: "kamran.maint",
    fullName: "Kamran Aslam",
    firstName: "Kamran",
    lastName: "Aslam",
    email: "kamran.maint@fahadweaving.com",
    phone: "+92 322 8844001",
    altPhone: "",
    dob: "1987-01-25",
    gender: "Male",
    role: "Manager",
    department: "Maintenance",
    designation: "Electrical Engineer",
    employeeId: "EMP-022",
    company: "ABC Textiles Ltd",
    branch: "Factory 02 - Faisalabad Industrial Estate",
    status: "Suspended",
    joiningDate: "2020-09-15",
    manager: "Ali Raza",
    shift: "Evening (14:00 - 23:00)",
    address: "Sargodha Road, Millat Colony",
    city: "Faisalabad",
    state: "Punjab",
    country: "Pakistan",
    postalCode: "38000",
    notes: "Account temporarily suspended pending audit inquiry regarding equipment maintenance logs.",
    avatar: "https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2027-09-15",
    lastLogin: "2026-09-10 11:20 AM",
    createdDate: "2020-09-15",
    twoFactorEnabled: false,
  },
  {
    id: "USR-013",
    username: "farhan.op",
    fullName: "Farhan Ali",
    firstName: "Farhan",
    lastName: "Ali",
    email: "farhan.op@fahadweaving.com",
    phone: "+92 312 4477889",
    altPhone: "",
    dob: "1998-12-04",
    gender: "Male",
    role: "Operator",
    department: "Production",
    designation: "Machine Operator",
    employeeId: "EMP-040",
    company: "ABC Weaving Mills Ltd",
    branch: "Factory 01 - SITE Industrial Area",
    status: "Active",
    joiningDate: "2024-01-10",
    manager: "Bilal Ahmed",
    shift: "Evening (14:00 - 23:00)",
    address: "Sector 11-E, Orangi Town",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "75800",
    notes: "Assigned to Airjet Looms AJ-01 through AJ-08.",
    avatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2027-01-10",
    lastLogin: "2026-09-27 10:15 PM",
    createdDate: "2024-01-10",
    twoFactorEnabled: false,
  },
  {
    id: "USR-014",
    username: "aisha.intern",
    fullName: "Aisha Malik",
    firstName: "Aisha",
    lastName: "Malik",
    email: "aisha.malik@fahadweaving.com",
    phone: "+92 335 1122334",
    altPhone: "",
    dob: "2002-06-20",
    gender: "Female",
    role: "Viewer",
    department: "Accounts",
    designation: "Accounts Trainee",
    employeeId: "EMP-055",
    company: "ABC Weaving Mills Ltd",
    branch: "Head Office - Karachi",
    status: "Pending",
    joiningDate: "2026-09-20",
    manager: "Hassan Khan",
    shift: "General (09:00 - 18:00)",
    address: "House 19, Street 3, Bahadurabad",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "74800",
    notes: "New joiner internship account. Awaiting HR document verification and background check approval.",
    avatar: "https://images.unsplash.com/photo-1534751516642-a171edd2521d?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2026-12-31",
    lastLogin: "—",
    createdDate: "2026-09-20",
    twoFactorEnabled: false,
  },
  {
    id: "USR-015",
    username: "rashid.shift",
    fullName: "Rashid Minhas",
    firstName: "Rashid",
    lastName: "Minhas",
    email: "rashid.shift@fahadweaving.com",
    phone: "+92 300 5511994",
    altPhone: "",
    dob: "1986-04-03",
    gender: "Male",
    role: "Supervisor",
    department: "Loom",
    designation: "Shift Incharge",
    employeeId: "EMP-038",
    company: "ABC Textiles Ltd",
    branch: "Factory 02 - Faisalabad Industrial Estate",
    status: "Active",
    joiningDate: "2021-10-05",
    manager: "Ali Raza",
    shift: "Night (22:00 - 07:00)",
    address: "Canal Road, Peoples Colony No 2",
    city: "Faisalabad",
    state: "Punjab",
    country: "Pakistan",
    postalCode: "38000",
    notes: "Night shift leader in charge of 32 shuttleless looms and raw beam mounts.",
    avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2028-10-05",
    lastLogin: "2026-09-28 05:45 AM",
    createdDate: "2021-10-05",
    twoFactorEnabled: false,
  },
  {
    id: "USR-016",
    username: "nabeel.audit",
    fullName: "Nabeel Javed",
    firstName: "Nabeel",
    lastName: "Javed",
    email: "nabeel.audit@fahadweaving.com",
    phone: "+92 321 7733441",
    altPhone: "",
    dob: "1984-11-19",
    gender: "Male",
    role: "Viewer",
    department: "Administration",
    designation: "Internal Auditor",
    employeeId: "EMP-012",
    company: "ABC Weaving Mills Ltd",
    branch: "Head Office - Karachi",
    status: "Active",
    joiningDate: "2020-05-12",
    manager: "Muhammad Ahmed",
    shift: "General (09:00 - 18:00)",
    address: "Plot 88, KDA Scheme 1",
    city: "Karachi",
    state: "Sindh",
    country: "Pakistan",
    postalCode: "75350",
    notes: "Performs quarterly compliance audits on cotton stock counts, payroll payouts, and scrap yarn reconciliation.",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80",
    accountExpiry: "2028-05-12",
    lastLogin: "2026-09-26 03:40 PM",
    createdDate: "2020-05-12",
    twoFactorEnabled: true,
  },
];

// Initial Realistic Activity Logs
export const INITIAL_ACTIVITIES = [
  {
    id: "act_101",
    timestamp: "28 Sep 2026, 10:42 AM",
    date: "2026-09-28",
    userId: "USR-001",
    username: "admin",
    userFullName: "Muhammad Ahmed",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    action: "Login",
    description: "Muhammad Ahmed successfully logged into ERP dashboard via 2FA authentication.",
    module: "Authentication",
    ipAddress: "192.168.1.10",
    device: "Chrome on macOS 15.1",
    status: "Success",
  },
  {
    id: "act_102",
    timestamp: "28 Sep 2026, 09:30 AM",
    date: "2026-09-28",
    userId: "USR-001",
    username: "admin",
    userFullName: "Muhammad Ahmed",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    action: "Role Changed",
    description: "Admin elevated Tariq Mehmood (tariq.sizing) from Operator to Supervisor.",
    module: "User Management",
    ipAddress: "192.168.1.10",
    device: "Chrome on macOS 15.1",
    status: "Success",
  },
  {
    id: "act_103",
    timestamp: "28 Sep 2026, 09:02 AM",
    date: "2026-09-28",
    userId: "USR-004",
    username: "hr.fatima",
    userFullName: "Fatima Noor",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    action: "Profile Updated",
    description: "Fatima Noor updated emergency contact numbers for 3 production shift supervisors.",
    module: "Workforce",
    ipAddress: "192.168.1.45",
    device: "Edge on Windows 11",
    status: "Success",
  },
  {
    id: "act_104",
    timestamp: "28 Sep 2026, 08:15 AM",
    date: "2026-09-28",
    userId: "USR-002",
    username: "production.manager",
    userFullName: "Ali Raza",
    userAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    action: "Login",
    description: "Ali Raza logged into Factory 01 terminal station.",
    module: "Authentication",
    ipAddress: "10.0.1.25",
    device: "Firefox on Ubuntu 24.04",
    status: "Success",
  },
  {
    id: "act_105",
    timestamp: "27 Sep 2026, 04:15 PM",
    date: "2026-09-27",
    userId: "USR-003",
    username: "accountant",
    userFullName: "Hassan Khan",
    userAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    action: "Password Changed",
    description: "Hassan Khan updated account security credentials following 90-day policy reminder.",
    module: "Security",
    ipAddress: "192.168.1.31",
    device: "Chrome on Windows 11",
    status: "Success",
  },
  {
    id: "act_106",
    timestamp: "27 Sep 2026, 02:20 PM",
    date: "2026-09-27",
    userId: "USR-001",
    username: "admin",
    userFullName: "Muhammad Ahmed",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    action: "Permission Updated",
    description: "Admin updated permissions for role 'Production Manager' adding 'inv.adjust' access.",
    module: "Roles & Permissions",
    ipAddress: "192.168.1.10",
    device: "Chrome on macOS 15.1",
    status: "Success",
  },
  {
    id: "act_107",
    timestamp: "26 Sep 2026, 11:10 AM",
    date: "2026-09-26",
    userId: "USR-004",
    username: "hr.fatima",
    userFullName: "Fatima Noor",
    userAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    action: "User Created",
    description: "Fatima Noor registered new trainee account for Aisha Malik (EMP-055).",
    module: "User Management",
    ipAddress: "192.168.1.45",
    device: "Edge on Windows 11",
    status: "Success",
  },
  {
    id: "act_108",
    timestamp: "25 Sep 2026, 05:40 PM",
    date: "2026-09-25",
    userId: "USR-001",
    username: "admin",
    userFullName: "Muhammad Ahmed",
    userAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    action: "User Deactivated",
    description: "Admin suspended Kamran Aslam (kamran.maint) account upon HR request.",
    module: "User Management",
    ipAddress: "192.168.1.10",
    device: "Chrome on macOS 15.1",
    status: "Success",
  },
  {
    id: "act_109",
    timestamp: "25 Sep 2026, 09:12 AM",
    date: "2026-09-25",
    userId: "USR-011",
    username: "zainab.it",
    userFullName: "Zainab Bibi",
    userAvatar: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    action: "Password Reset UI",
    description: "Zainab Bibi initiated password reset link for supervisor Bilal Ahmed.",
    module: "User Management",
    ipAddress: "192.168.1.80",
    device: "Chrome on Windows 11",
    status: "Success",
  },
  {
    id: "act_110",
    timestamp: "24 Sep 2026, 08:00 PM",
    date: "2026-09-24",
    userId: "USR-013",
    username: "farhan.op",
    userFullName: "Farhan Ali",
    userAvatar: "https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=150&auto=format&fit=crop&q=80",
    action: "Logout",
    description: "Farhan Ali logged out at the end of evening shift.",
    module: "Authentication",
    ipAddress: "10.0.1.40",
    device: "Loom Terminal 04",
    status: "Success",
  },
];
