/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './container/__root'
import { Route as IndexRouteImport } from './container/index'
import { Route as UserManagementIndexRouteImport } from './container/user-management/index'
import { Route as SettingsIndexRouteImport } from './container/settings/index'
import { Route as SaleIndexRouteImport } from './container/sale/index'
import { Route as ReportsIndexRouteImport } from './container/reports/index'
import { Route as PurchaseIndexRouteImport } from './container/purchase/index'
import { Route as InventoryIndexRouteImport } from './container/inventory/index'
import { Route as DashboardIndexRouteImport } from './container/dashboard/index'
import { Route as DailyLedgerIndexRouteImport } from './container/daily-ledger/index'
import { Route as AuthIndexRouteImport } from './container/auth/index'
import { Route as ActivityLogIndexRouteImport } from './container/activity-log/index'
import { Route as UserManagementActivityRouteImport } from './container/user-management/activity'
import { Route as SaleCustomerRouteImport } from './container/sale/customer'
import { Route as PurchaseSupplierRouteImport } from './container/purchase/supplier'
import { Route as HrPayrollRouteImport } from './container/hr/payroll'
import { Route as HrMarkAttendanceRouteImport } from './container/hr/mark-attendance'
import { Route as HrEmployeesRouteImport } from './container/hr/employees'
import { Route as HrEmployeeSalaryRouteImport } from './container/hr/employee-salary'
import { Route as HrAttendanceRouteImport } from './container/hr/attendance'
import { Route as AuthSignupRouteImport } from './container/auth/signup'
import { Route as AuthLoginRouteImport } from './container/auth/login'
import { Route as UserManagementUsersIndexRouteImport } from './container/user-management/users.index'
import { Route as UserManagementRolesIndexRouteImport } from './container/user-management/roles.index'
import { Route as ProductionSizingIndexRouteImport } from './container/production/sizing/index'
import { Route as ProductionRawManufacturingIndexRouteImport } from './container/production/raw-manufacturing/index'
import { Route as ProductionLoomIndexRouteImport } from './container/production/loom/index'
import { Route as ProductionBeamIndexRouteImport } from './container/production/beam/index'
import { Route as HrEmployeesIndexRouteImport } from './container/hr/employees.index'
import { Route as UserManagementUsersAddRouteImport } from './container/user-management/users.add'
import { Route as UserManagementUsersUserIdRouteImport } from './container/user-management/users.$userId'
import { Route as UserManagementRolesAddRouteImport } from './container/user-management/roles.add'
import { Route as UserManagementRolesRoleIdRouteImport } from './container/user-management/roles.$roleId'
import { Route as HrEmployeesAddRouteImport } from './container/hr/employees.add'
import { Route as HrEmployeesEmployeeIdRouteImport } from './container/hr/employees.$employeeId'
import { Route as UserManagementUsersUserIdIndexRouteImport } from './container/user-management/users.$userId.index'
import { Route as UserManagementUsersUserIdEditRouteImport } from './container/user-management/users.$userId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementIndexRoute = UserManagementIndexRouteImport.update({
  id: '/user-management/',
  path: '/user-management/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleIndexRoute = SaleIndexRouteImport.update({
  id: '/sale/',
  path: '/sale/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseIndexRoute = PurchaseIndexRouteImport.update({
  id: '/purchase/',
  path: '/purchase/',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyLedgerIndexRoute = DailyLedgerIndexRouteImport.update({
  id: '/daily-ledger/',
  path: '/daily-ledger/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityLogIndexRoute = ActivityLogIndexRouteImport.update({
  id: '/activity-log/',
  path: '/activity-log/',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementActivityRoute = UserManagementActivityRouteImport.update({
  id: '/user-management/activity',
  path: '/user-management/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleCustomerRoute = SaleCustomerRouteImport.update({
  id: '/sale/customer',
  path: '/sale/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseSupplierRoute = PurchaseSupplierRouteImport.update({
  id: '/purchase/supplier',
  path: '/purchase/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const HrPayrollRoute = HrPayrollRouteImport.update({
  id: '/hr/payroll',
  path: '/hr/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const HrMarkAttendanceRoute = HrMarkAttendanceRouteImport.update({
  id: '/hr/mark-attendance',
  path: '/hr/mark-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEmployeesRoute = HrEmployeesRouteImport.update({
  id: '/hr/employees',
  path: '/hr/employees',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEmployeeSalaryRoute = HrEmployeeSalaryRouteImport.update({
  id: '/hr/employee-salary',
  path: '/hr/employee-salary',
  getParentRoute: () => rootRouteImport,
} as any)
const HrAttendanceRoute = HrAttendanceRouteImport.update({
  id: '/hr/attendance',
  path: '/hr/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementUsersIndexRoute =
  UserManagementUsersIndexRouteImport.update({
    id: '/user-management/users/',
    path: '/user-management/users/',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserManagementRolesIndexRoute =
  UserManagementRolesIndexRouteImport.update({
    id: '/user-management/roles/',
    path: '/user-management/roles/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductionSizingIndexRoute = ProductionSizingIndexRouteImport.update({
  id: '/production/sizing/',
  path: '/production/sizing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRawManufacturingIndexRoute =
  ProductionRawManufacturingIndexRouteImport.update({
    id: '/production/raw-manufacturing/',
    path: '/production/raw-manufacturing/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProductionLoomIndexRoute = ProductionLoomIndexRouteImport.update({
  id: '/production/loom/',
  path: '/production/loom/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionBeamIndexRoute = ProductionBeamIndexRouteImport.update({
  id: '/production/beam/',
  path: '/production/beam/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrEmployeesIndexRoute = HrEmployeesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HrEmployeesRoute,
} as any)
const UserManagementUsersAddRoute = UserManagementUsersAddRouteImport.update({
  id: '/user-management/users/add',
  path: '/user-management/users/add',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementUsersUserIdRoute =
  UserManagementUsersUserIdRouteImport.update({
    id: '/user-management/users/$userId',
    path: '/user-management/users/$userId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UserManagementRolesAddRoute = UserManagementRolesAddRouteImport.update({
  id: '/user-management/roles/add',
  path: '/user-management/roles/add',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRolesRoleIdRoute =
  UserManagementRolesRoleIdRouteImport.update({
    id: '/user-management/roles/$roleId',
    path: '/user-management/roles/$roleId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HrEmployeesAddRoute = HrEmployeesAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => HrEmployeesRoute,
} as any)
const HrEmployeesEmployeeIdRoute = HrEmployeesEmployeeIdRouteImport.update({
  id: '/$employeeId',
  path: '/$employeeId',
  getParentRoute: () => HrEmployeesRoute,
} as any)
const UserManagementUsersUserIdIndexRoute =
  UserManagementUsersUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => UserManagementUsersUserIdRoute,
  } as any)
const UserManagementUsersUserIdEditRoute =
  UserManagementUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => UserManagementUsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/employee-salary': typeof HrEmployeeSalaryRoute
  '/hr/employees': typeof HrEmployeesRouteWithChildren
  '/hr/mark-attendance': typeof HrMarkAttendanceRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/purchase/supplier': typeof PurchaseSupplierRoute
  '/sale/customer': typeof SaleCustomerRoute
  '/user-management/activity': typeof UserManagementActivityRoute
  '/activity-log/': typeof ActivityLogIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/daily-ledger/': typeof DailyLedgerIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/purchase/': typeof PurchaseIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sale/': typeof SaleIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
  '/hr/employees/$employeeId': typeof HrEmployeesEmployeeIdRoute
  '/hr/employees/add': typeof HrEmployeesAddRoute
  '/user-management/roles/$roleId': typeof UserManagementRolesRoleIdRoute
  '/user-management/roles/add': typeof UserManagementRolesAddRoute
  '/user-management/users/$userId': typeof UserManagementUsersUserIdRouteWithChildren
  '/user-management/users/add': typeof UserManagementUsersAddRoute
  '/hr/employees/': typeof HrEmployeesIndexRoute
  '/production/beam/': typeof ProductionBeamIndexRoute
  '/production/loom/': typeof ProductionLoomIndexRoute
  '/production/raw-manufacturing/': typeof ProductionRawManufacturingIndexRoute
  '/production/sizing/': typeof ProductionSizingIndexRoute
  '/user-management/roles/': typeof UserManagementRolesIndexRoute
  '/user-management/users/': typeof UserManagementUsersIndexRoute
  '/user-management/users/$userId/edit': typeof UserManagementUsersUserIdEditRoute
  '/user-management/users/$userId/': typeof UserManagementUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/employee-salary': typeof HrEmployeeSalaryRoute
  '/hr/mark-attendance': typeof HrMarkAttendanceRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/purchase/supplier': typeof PurchaseSupplierRoute
  '/sale/customer': typeof SaleCustomerRoute
  '/user-management/activity': typeof UserManagementActivityRoute
  '/activity-log': typeof ActivityLogIndexRoute
  '/auth': typeof AuthIndexRoute
  '/daily-ledger': typeof DailyLedgerIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/purchase': typeof PurchaseIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/sale': typeof SaleIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/user-management': typeof UserManagementIndexRoute
  '/hr/employees/$employeeId': typeof HrEmployeesEmployeeIdRoute
  '/hr/employees/add': typeof HrEmployeesAddRoute
  '/user-management/roles/$roleId': typeof UserManagementRolesRoleIdRoute
  '/user-management/roles/add': typeof UserManagementRolesAddRoute
  '/user-management/users/add': typeof UserManagementUsersAddRoute
  '/hr/employees': typeof HrEmployeesIndexRoute
  '/production/beam': typeof ProductionBeamIndexRoute
  '/production/loom': typeof ProductionLoomIndexRoute
  '/production/raw-manufacturing': typeof ProductionRawManufacturingIndexRoute
  '/production/sizing': typeof ProductionSizingIndexRoute
  '/user-management/roles': typeof UserManagementRolesIndexRoute
  '/user-management/users': typeof UserManagementUsersIndexRoute
  '/user-management/users/$userId/edit': typeof UserManagementUsersUserIdEditRoute
  '/user-management/users/$userId': typeof UserManagementUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/hr/attendance': typeof HrAttendanceRoute
  '/hr/employee-salary': typeof HrEmployeeSalaryRoute
  '/hr/employees': typeof HrEmployeesRouteWithChildren
  '/hr/mark-attendance': typeof HrMarkAttendanceRoute
  '/hr/payroll': typeof HrPayrollRoute
  '/purchase/supplier': typeof PurchaseSupplierRoute
  '/sale/customer': typeof SaleCustomerRoute
  '/user-management/activity': typeof UserManagementActivityRoute
  '/activity-log/': typeof ActivityLogIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/daily-ledger/': typeof DailyLedgerIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/purchase/': typeof PurchaseIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/sale/': typeof SaleIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/user-management/': typeof UserManagementIndexRoute
  '/hr/employees/$employeeId': typeof HrEmployeesEmployeeIdRoute
  '/hr/employees/add': typeof HrEmployeesAddRoute
  '/user-management/roles/$roleId': typeof UserManagementRolesRoleIdRoute
  '/user-management/roles/add': typeof UserManagementRolesAddRoute
  '/user-management/users/$userId': typeof UserManagementUsersUserIdRouteWithChildren
  '/user-management/users/add': typeof UserManagementUsersAddRoute
  '/hr/employees/': typeof HrEmployeesIndexRoute
  '/production/beam/': typeof ProductionBeamIndexRoute
  '/production/loom/': typeof ProductionLoomIndexRoute
  '/production/raw-manufacturing/': typeof ProductionRawManufacturingIndexRoute
  '/production/sizing/': typeof ProductionSizingIndexRoute
  '/user-management/roles/': typeof UserManagementRolesIndexRoute
  '/user-management/users/': typeof UserManagementUsersIndexRoute
  '/user-management/users/$userId/edit': typeof UserManagementUsersUserIdEditRoute
  '/user-management/users/$userId/': typeof UserManagementUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/hr/attendance'
    | '/hr/employee-salary'
    | '/hr/employees'
    | '/hr/mark-attendance'
    | '/hr/payroll'
    | '/purchase/supplier'
    | '/sale/customer'
    | '/user-management/activity'
    | '/activity-log/'
    | '/auth/'
    | '/daily-ledger/'
    | '/dashboard/'
    | '/inventory/'
    | '/purchase/'
    | '/reports/'
    | '/sale/'
    | '/settings/'
    | '/user-management/'
    | '/hr/employees/$employeeId'
    | '/hr/employees/add'
    | '/user-management/roles/$roleId'
    | '/user-management/roles/add'
    | '/user-management/users/$userId'
    | '/user-management/users/add'
    | '/hr/employees/'
    | '/production/beam/'
    | '/production/loom/'
    | '/production/raw-manufacturing/'
    | '/production/sizing/'
    | '/user-management/roles/'
    | '/user-management/users/'
    | '/user-management/users/$userId/edit'
    | '/user-management/users/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/hr/attendance'
    | '/hr/employee-salary'
    | '/hr/mark-attendance'
    | '/hr/payroll'
    | '/purchase/supplier'
    | '/sale/customer'
    | '/user-management/activity'
    | '/activity-log'
    | '/auth'
    | '/daily-ledger'
    | '/dashboard'
    | '/inventory'
    | '/purchase'
    | '/reports'
    | '/sale'
    | '/settings'
    | '/user-management'
    | '/hr/employees/$employeeId'
    | '/hr/employees/add'
    | '/user-management/roles/$roleId'
    | '/user-management/roles/add'
    | '/user-management/users/add'
    | '/hr/employees'
    | '/production/beam'
    | '/production/loom'
    | '/production/raw-manufacturing'
    | '/production/sizing'
    | '/user-management/roles'
    | '/user-management/users'
    | '/user-management/users/$userId/edit'
    | '/user-management/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/hr/attendance'
    | '/hr/employee-salary'
    | '/hr/employees'
    | '/hr/mark-attendance'
    | '/hr/payroll'
    | '/purchase/supplier'
    | '/sale/customer'
    | '/user-management/activity'
    | '/activity-log/'
    | '/auth/'
    | '/daily-ledger/'
    | '/dashboard/'
    | '/inventory/'
    | '/purchase/'
    | '/reports/'
    | '/sale/'
    | '/settings/'
    | '/user-management/'
    | '/hr/employees/$employeeId'
    | '/hr/employees/add'
    | '/user-management/roles/$roleId'
    | '/user-management/roles/add'
    | '/user-management/users/$userId'
    | '/user-management/users/add'
    | '/hr/employees/'
    | '/production/beam/'
    | '/production/loom/'
    | '/production/raw-manufacturing/'
    | '/production/sizing/'
    | '/user-management/roles/'
    | '/user-management/users/'
    | '/user-management/users/$userId/edit'
    | '/user-management/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  HrAttendanceRoute: typeof HrAttendanceRoute
  HrEmployeeSalaryRoute: typeof HrEmployeeSalaryRoute
  HrEmployeesRoute: typeof HrEmployeesRouteWithChildren
  HrMarkAttendanceRoute: typeof HrMarkAttendanceRoute
  HrPayrollRoute: typeof HrPayrollRoute
  PurchaseSupplierRoute: typeof PurchaseSupplierRoute
  SaleCustomerRoute: typeof SaleCustomerRoute
  UserManagementActivityRoute: typeof UserManagementActivityRoute
  ActivityLogIndexRoute: typeof ActivityLogIndexRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DailyLedgerIndexRoute: typeof DailyLedgerIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  InventoryIndexRoute: typeof InventoryIndexRoute
  PurchaseIndexRoute: typeof PurchaseIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  SaleIndexRoute: typeof SaleIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  UserManagementIndexRoute: typeof UserManagementIndexRoute
  UserManagementRolesRoleIdRoute: typeof UserManagementRolesRoleIdRoute
  UserManagementRolesAddRoute: typeof UserManagementRolesAddRoute
  UserManagementUsersUserIdRoute: typeof UserManagementUsersUserIdRouteWithChildren
  UserManagementUsersAddRoute: typeof UserManagementUsersAddRoute
  ProductionBeamIndexRoute: typeof ProductionBeamIndexRoute
  ProductionLoomIndexRoute: typeof ProductionLoomIndexRoute
  ProductionRawManufacturingIndexRoute: typeof ProductionRawManufacturingIndexRoute
  ProductionSizingIndexRoute: typeof ProductionSizingIndexRoute
  UserManagementRolesIndexRoute: typeof UserManagementRolesIndexRoute
  UserManagementUsersIndexRoute: typeof UserManagementUsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/': {
      id: '/user-management/'
      path: '/user-management'
      fullPath: '/user-management/'
      preLoaderRoute: typeof UserManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/': {
      id: '/sale/'
      path: '/sale'
      fullPath: '/sale/'
      preLoaderRoute: typeof SaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/': {
      id: '/purchase/'
      path: '/purchase'
      fullPath: '/purchase/'
      preLoaderRoute: typeof PurchaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-ledger/': {
      id: '/daily-ledger/'
      path: '/daily-ledger'
      fullPath: '/daily-ledger/'
      preLoaderRoute: typeof DailyLedgerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity-log/': {
      id: '/activity-log/'
      path: '/activity-log'
      fullPath: '/activity-log/'
      preLoaderRoute: typeof ActivityLogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/activity': {
      id: '/user-management/activity'
      path: '/user-management/activity'
      fullPath: '/user-management/activity'
      preLoaderRoute: typeof UserManagementActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale/customer': {
      id: '/sale/customer'
      path: '/sale/customer'
      fullPath: '/sale/customer'
      preLoaderRoute: typeof SaleCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/supplier': {
      id: '/purchase/supplier'
      path: '/purchase/supplier'
      fullPath: '/purchase/supplier'
      preLoaderRoute: typeof PurchaseSupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/payroll': {
      id: '/hr/payroll'
      path: '/hr/payroll'
      fullPath: '/hr/payroll'
      preLoaderRoute: typeof HrPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/mark-attendance': {
      id: '/hr/mark-attendance'
      path: '/hr/mark-attendance'
      fullPath: '/hr/mark-attendance'
      preLoaderRoute: typeof HrMarkAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/employees': {
      id: '/hr/employees'
      path: '/hr/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof HrEmployeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/employee-salary': {
      id: '/hr/employee-salary'
      path: '/hr/employee-salary'
      fullPath: '/hr/employee-salary'
      preLoaderRoute: typeof HrEmployeeSalaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/attendance': {
      id: '/hr/attendance'
      path: '/hr/attendance'
      fullPath: '/hr/attendance'
      preLoaderRoute: typeof HrAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/users/': {
      id: '/user-management/users/'
      path: '/user-management/users'
      fullPath: '/user-management/users/'
      preLoaderRoute: typeof UserManagementUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/roles/': {
      id: '/user-management/roles/'
      path: '/user-management/roles'
      fullPath: '/user-management/roles/'
      preLoaderRoute: typeof UserManagementRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/sizing/': {
      id: '/production/sizing/'
      path: '/production/sizing'
      fullPath: '/production/sizing/'
      preLoaderRoute: typeof ProductionSizingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/raw-manufacturing/': {
      id: '/production/raw-manufacturing/'
      path: '/production/raw-manufacturing'
      fullPath: '/production/raw-manufacturing/'
      preLoaderRoute: typeof ProductionRawManufacturingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/loom/': {
      id: '/production/loom/'
      path: '/production/loom'
      fullPath: '/production/loom/'
      preLoaderRoute: typeof ProductionLoomIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production/beam/': {
      id: '/production/beam/'
      path: '/production/beam'
      fullPath: '/production/beam/'
      preLoaderRoute: typeof ProductionBeamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/employees/': {
      id: '/hr/employees/'
      path: '/'
      fullPath: '/hr/employees/'
      preLoaderRoute: typeof HrEmployeesIndexRouteImport
      parentRoute: typeof HrEmployeesRoute
    }
    '/user-management/users/add': {
      id: '/user-management/users/add'
      path: '/user-management/users/add'
      fullPath: '/user-management/users/add'
      preLoaderRoute: typeof UserManagementUsersAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/users/$userId': {
      id: '/user-management/users/$userId'
      path: '/user-management/users/$userId'
      fullPath: '/user-management/users/$userId'
      preLoaderRoute: typeof UserManagementUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/roles/add': {
      id: '/user-management/roles/add'
      path: '/user-management/roles/add'
      fullPath: '/user-management/roles/add'
      preLoaderRoute: typeof UserManagementRolesAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management/roles/$roleId': {
      id: '/user-management/roles/$roleId'
      path: '/user-management/roles/$roleId'
      fullPath: '/user-management/roles/$roleId'
      preLoaderRoute: typeof UserManagementRolesRoleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/employees/add': {
      id: '/hr/employees/add'
      path: '/add'
      fullPath: '/hr/employees/add'
      preLoaderRoute: typeof HrEmployeesAddRouteImport
      parentRoute: typeof HrEmployeesRoute
    }
    '/hr/employees/$employeeId': {
      id: '/hr/employees/$employeeId'
      path: '/$employeeId'
      fullPath: '/hr/employees/$employeeId'
      preLoaderRoute: typeof HrEmployeesEmployeeIdRouteImport
      parentRoute: typeof HrEmployeesRoute
    }
    '/user-management/users/$userId/': {
      id: '/user-management/users/$userId/'
      path: '/'
      fullPath: '/user-management/users/$userId/'
      preLoaderRoute: typeof UserManagementUsersUserIdIndexRouteImport
      parentRoute: typeof UserManagementUsersUserIdRoute
    }
    '/user-management/users/$userId/edit': {
      id: '/user-management/users/$userId/edit'
      path: '/edit'
      fullPath: '/user-management/users/$userId/edit'
      preLoaderRoute: typeof UserManagementUsersUserIdEditRouteImport
      parentRoute: typeof UserManagementUsersUserIdRoute
    }
  }
}

interface HrEmployeesRouteChildren {
  HrEmployeesEmployeeIdRoute: typeof HrEmployeesEmployeeIdRoute
  HrEmployeesAddRoute: typeof HrEmployeesAddRoute
  HrEmployeesIndexRoute: typeof HrEmployeesIndexRoute
}

const HrEmployeesRouteChildren: HrEmployeesRouteChildren = {
  HrEmployeesEmployeeIdRoute: HrEmployeesEmployeeIdRoute,
  HrEmployeesAddRoute: HrEmployeesAddRoute,
  HrEmployeesIndexRoute: HrEmployeesIndexRoute,
}

const HrEmployeesRouteWithChildren = HrEmployeesRoute._addFileChildren(
  HrEmployeesRouteChildren,
)

interface UserManagementUsersUserIdRouteChildren {
  UserManagementUsersUserIdEditRoute: typeof UserManagementUsersUserIdEditRoute
  UserManagementUsersUserIdIndexRoute: typeof UserManagementUsersUserIdIndexRoute
}

const UserManagementUsersUserIdRouteChildren: UserManagementUsersUserIdRouteChildren =
  {
    UserManagementUsersUserIdEditRoute: UserManagementUsersUserIdEditRoute,
    UserManagementUsersUserIdIndexRoute: UserManagementUsersUserIdIndexRoute,
  }

const UserManagementUsersUserIdRouteWithChildren =
  UserManagementUsersUserIdRoute._addFileChildren(
    UserManagementUsersUserIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  HrAttendanceRoute: HrAttendanceRoute,
  HrEmployeeSalaryRoute: HrEmployeeSalaryRoute,
  HrEmployeesRoute: HrEmployeesRouteWithChildren,
  HrMarkAttendanceRoute: HrMarkAttendanceRoute,
  HrPayrollRoute: HrPayrollRoute,
  PurchaseSupplierRoute: PurchaseSupplierRoute,
  SaleCustomerRoute: SaleCustomerRoute,
  UserManagementActivityRoute: UserManagementActivityRoute,
  ActivityLogIndexRoute: ActivityLogIndexRoute,
  AuthIndexRoute: AuthIndexRoute,
  DailyLedgerIndexRoute: DailyLedgerIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  InventoryIndexRoute: InventoryIndexRoute,
  PurchaseIndexRoute: PurchaseIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  SaleIndexRoute: SaleIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  UserManagementIndexRoute: UserManagementIndexRoute,
  UserManagementRolesRoleIdRoute: UserManagementRolesRoleIdRoute,
  UserManagementRolesAddRoute: UserManagementRolesAddRoute,
  UserManagementUsersUserIdRoute: UserManagementUsersUserIdRouteWithChildren,
  UserManagementUsersAddRoute: UserManagementUsersAddRoute,
  ProductionBeamIndexRoute: ProductionBeamIndexRoute,
  ProductionLoomIndexRoute: ProductionLoomIndexRoute,
  ProductionRawManufacturingIndexRoute: ProductionRawManufacturingIndexRoute,
  ProductionSizingIndexRoute: ProductionSizingIndexRoute,
  UserManagementRolesIndexRoute: UserManagementRolesIndexRoute,
  UserManagementUsersIndexRoute: UserManagementUsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
